# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: skeptic 0.0.16 ruby lib

Gem::Specification.new do |s|
  s.name = "hivemind"
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alexander Ivanov"]
  s.date = "2016-03-12"
  s.description = "A multi-syntax programming language"
  s.email = "alehande42@gmail.com"
  s.executables = ["hivemind"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "bin/hivemind",
    "lib/hivemind.rb",
    ".gitignore",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "hivemind.gemspec",
    "lib/hivemind/code_viewer.rb",
    "lib/hivemind/combinators.rb",
    "lib/hivemind/environment.rb",
    "lib/hivemind/errors.rb",
    "lib/hivemind/renderer.rb",
    "lib/hivemind/runtime.rb",
    "lib/hivemind/syntax.rb",
    "lib/hivemind/universal_ast.rb",
    "lib/hivemind/vm.rb",
    "spec/spec_helper.rb",
    "spec/hivemind/parser_spec.rb",
    "spec/hivemind/vm_spec.rb",
    "spec/hivemind/universal_ast_spec.rb",
    "syntaxes/pythonic.syntax",
    "syntaxes/lolcode.syntax",
    "syntaxes/paren.syntax"
  ]
  s.homepage = "http://github.com/alehander42/hivemind"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "A multi-syntax language"

  s.add_development_dependency(%q<rspec>, ["= 2.14.1"])
  s.add_development_dependency(%q<bundler>, [">= 0"])
  s.add_development_dependency(%q<skeptic>, [">= 0"])
end

